// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6S6g0IhP42oWBUurdGqLcDtKSGnsoYKg',
    appId: '1:31595876234:web:a0981384c9658873aa4273',
    messagingSenderId: '31595876234',
    projectId: 'donations-list',
    authDomain: 'donations-list.firebaseapp.com',
    storageBucket: 'donations-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiRAcLP4Y6DwFgcrHsUlRfXyC0juVeA0',
    appId: '1:31595876234:android:dee45a86c6696730aa4273',
    messagingSenderId: '31595876234',
    projectId: 'donations-list',
    storageBucket: 'donations-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzawlDEkIFTuhznR4kLxT4Cfpt_K8Wins',
    appId: '1:31595876234:ios:f2feae4da2131c06aa4273',
    messagingSenderId: '31595876234',
    projectId: 'donations-list',
    storageBucket: 'donations-list.appspot.com',
    iosBundleId: 'com.example.donationsList',
  );
}
